name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: "8.1"
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Configure application
      run: |
        php artisan cache:clear
        php artisan config:clear
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USERNAME }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          cd /var/www/laravel/laravel-api
          echo "Deploying application ..."
          git clone https://github.com/farmzoneAfrica/laravel-api.git
          git reset --hard HEAD
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan optimize
          echo "" | sudo -S service php8.1-fpm reload
          echo "Application deployed!"

